CWE 862
hmcts/cpo-case-payment-orders-api pull request #156
Opened 2022-02-28 10:54 UTC by A-R05

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CCD-2696

### Change description ###

CWE-862

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2022-03-28 12:34 UTC, MSancaktutar approved these changes

2022-03-28 13:29 UTC, paulridout approved these changes
Changes look OK.

2022-03-28 14:54 UTC, paulridout approved these changes
Changes look OK.

2022-04-08 10:52 UTC, paulridout requested changes
Does the update of the spring-framework.version property fix CVE-2022-22965?  If so it should be removed from the suppressions file.  If not, add `until="2022-04-25"` to the CVE-2022-22965 suppression.

2022-04-08 11:11 UTC, duranmf commented
> Does the update of the spring-framework.version property fix [CVE-2022-22965](https://github.com/advisories/GHSA-36p3-wjmg-h94x)? If so it should be removed from the suppressions file. If not, add `until="2022-04-25"` to the [CVE-2022-22965](https://github.com/advisories/GHSA-36p3-wjmg-h94x) suppression.

you are right, just removed that tag.

2022-04-08 12:31 UTC, paulridout approved these changes
Changes look OK.

2022-04-08 16:15 UTC, MSancaktutar approved these changes
LGTM - with 1 minor comment

2022-04-25 10:10 UTC, hemantt approved these changes

2022-04-26 01:45 UTC, merged